# Nombre del microservicio
spring.application.name=mailservice

# Puerto del microservicio
server.port=8081

# Configuración SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=beritozambrano@gmail.com
spring.mail.password=fktganhokvcpiowm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

# Logging opcional para debug
logging.level.org.springframework.mail=DEBUG

logging.level.org.springframework.web.servlet.mvc.method.annotation=TRACE